# Generated by Django 2.2.7 on 2019-11-22 21:15

import Documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=Documents.models.upload_image_path)),
                ('defa', models.BooleanField(default=True)),
            ],
        ),
    ]
